meta_product_name: "Gala Thevenet"
meta_title: "Gala Thevenet - Fullstack web developper"
meta_description: "Check out my website to know better about me and my past and current projects."
meta_image: "metapic.jpg" # should exist in `app/assets/images/`
